# Labels from the original data set weren't associated to the good flower species, we add to index them again
# Ref : https://www.robots.ox.ac.uk/~vgg/data/flowers/102/categories.html

labels = {
    1 : 'Pink primrose',
    2 : 'Hard-leaved pocket orchid',
    3 : 'Canterbury bells',
    4 : 'Sweet pea',
    5 : 'English marigold',
    6 : 'Tiger lily',
    7 : 'Moon orchid',
    8 : 'Bird of paradise',
    9 : 'Monkshood',
    10 : 'Globe thistle',
    11 : 'Snapdragon',
    12 : 'Colt\'s foot',
    13 : 'King protea',
    14 : 'Spear thistle',
    15 : 'Yellow iris',
    16 : 'Globe-flower',
    17 : 'Purple coneflower',
    18 : 'Peruvian lily',
    19 : 'Balloon flower',
    20 : 'Giant white arum lily',
    21 : 'Fire lily',
    22 : 'Pincushion flower',
    23 : 'Fritillary',
    24 : 'Red ginger',
    25 : 'Grape hyacinth',
    26 : 'Corn poppy',
    27 : 'Prince of wales feathers',
    28 : 'Stemless gentian',
    29 : 'Artichoke',
    30 : 'Sweet william',
    31 : 'Carnation',
    32 : 'Garden phlox',
    33 : 'Love in the mist',
    34 : 'Mexican aster',
    35 : 'Alpine sea holly',
    36 : 'Ruby-lipped cattleya',
    37 : 'Cape flower',
    38 : 'Great masterwort',
    39 : 'Siam tulip',
    40 : 'Lenten rose',
    41 : 'Barbeton daisy',
    42 : 'Daffodil',
    43 : 'Sword lily',
    44 : 'Poinsettia',
    45 : 'Bolero deep blue',
    46 : 'Wallflower',
    47 : 'Marigold',
    48 : 'Buttercup',
    49 : 'Oxeye daisy',
    50 : 'Common dandelion',
    51 : 'Petunia',
    52 : 'Wild pansy',
    53 : 'Primula',
    54 : 'Sunflower',
    55 : 'Pelargonium',
    56 : 'Bishop of llandaff',
    57 : 'Gaura',
    58 : 'Geranium',
    59 : 'Orange dahlia',
    60 : 'Pink-yellow dahlia',
    61 : 'Cautleya spicata',
    62 : 'Japanese anemone',
    63 : 'Black-eyed susan',
    64 : 'Silverbush',
    65 : 'Californian poppy',
    66 : 'Osteospermum',
    67 : 'Spring crocus',
    68 : 'Bearded iris',
    69 : 'Windflower',
    70 : 'Tree poppy',
    71 : 'Gazania',
    72 : 'Azalea',
    73 : 'Water lily',
    74 : 'Rose',
    75 : 'Thorn apple',
    76 : 'Morning glory',
    77 : 'Passion flower',
    78 : 'Lotus',
    79 : 'Toad lily',
    80 : 'Anthurium',
    81 : 'Frangipani',
    82 : 'Clematis',
    83 : 'Hibiscus',
    84 : 'Columbine',
    85 : 'Desert-rose',
    86 : 'Tree mallow',
    87 : 'Magnolia',
    88 : 'Cyclamen',
    89 : 'Watercress',
    90 : 'Canna lily',
    91 : 'Hippeastrum',
    92 : 'Bee balm',
    93 : 'Ball moss',
    94 : 'Foxglove',
    95 : 'Bougainvillea',
    96 : 'Camellia',
    97 : 'Mallow',
    98 : 'Mexican petunia',
    99 : 'Bromelia',
    100 : 'Blanket flower',
    101 : 'Trumpet creeper',
    102 : 'Blackberry lily',
}